version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories:
      - "e2e/"
      - "www/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directories:
      - ".github/**/*"
    schedule:
      interval: "weekly"
