version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-upgrades:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directories:
      - "e2e/"
      - "www/**"
    schedule:
      interval: "daily"
    groups:
      minor-upgrades:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    groups:
      minor-upgrades:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-upgrades:
        update-types:
          - "minor"
          - "patch"
