name: CI
on:
  push:
    branches:
    - fake_master
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: ${{ matrix.host-version }} / python ${{ matrix.python-version }}
    runs-on: ${{ matrix.host-version }}

    strategy:
      fail-fast: false
      matrix:
        host-version:
          - windows-2019
          - windows-2022
          - ubuntu-latest
          - macos-13  # latest is m1
          - macos-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    env:
      # Needed to ignore specific warns, otherwise, it'll warn a generic message
      SQLALCHEMY_WARN_20: 1

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'pip'
          cache-dependency-path: |
            requirements-ci.txt
            requirements-cidb.txt
            master/setup.py
            worker/setup.py
            pkg/setup.py

      - name: "Install dependencies"
        run: |
          python -c "import sys; print(sys.prefix)"
          python -c "import sys; print(sys.exec_prefix)"
          python -c "import sys; print(sys.executable)"
          python -V -V
          python -m pip install -r requirements-pip.txt
          python -m pip install -r requirements-ci.txt
          python -m pip list

      - name: "Check win32api"
        if: ${{ contains(matrix.host-version, 'windows') }}
        run: |
          # Check that pywin32 is properly installed
          python -c "import win32api"

      - name: "Run tests for ${{ matrix.python-version }}"
        run: "python -m twisted.trial -j4 --reporter=text --rterrors buildbot.test buildbot_worker.test"
        timeout-minutes: 30
